### ISSUE TITLE
Missing mergeschemas.py

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/ETL#1]
> mergeschemas.py then merges all these schemas into one schema that defines the dicom_all table.

@G-White-ISB I just noticed this file is missing from the repo. Can you add it for the sake of completeness?

**Comment by s-paquette** [comment]
Before it's added to the repo, can I get an understanding of what it is? (We don't typically add one-off use scripts to the repo long-term if they're for building a temporary set of data; we'll archive them into Google Drive or add them to an ETL repo.)

**Comment by G-White-ISB** [comment]
Hi,
So Suzanne we had already created a separate repo just for putting in ETL:
https://github.com/ImagingDataCommons/ETL. mergeschemas.py has been added.
Geirge

**Comment by s-paquette** [comment]
Perfect!

**Comment by fedorov** [comment]
Thank you!
