### ISSUE TITLE
[clinical] table prefix should use idc_webapp_collection_id from original_collections_metadata

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/ETL#19]
Currently, those prefixes are based on a heuristic applied to the wiki collection IDs.

<img width="191" alt="image" src="https://user-images.githubusercontent.com/313942/154330295-04f9ea26-0bef-4892-97c5-8419e95069ee.png">

This can be done using join of the table in `clinical_notes.json` on `tcia_wiki_collection_id` with `bigquery-public-data:idc_current.original_collections_metadata`

**Comment by fedorov** [comment]
also, column `collection` in per-collection clinical table, should instead be `collection_id`, and should point to the `idc_webapp_collection_id` version of collection_id.

**Comment by G-White-ISB** [comment]
The tables are now named using the idc_webapp_collecion_id in the idc-dev-etl.clinical dataset
