### ISSUE TITLE
[clinical] Improve harmonization of ACRIN and non-ACRIN tables schema

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/ETL#20]
I suggest it makes sense to do the following:
* remove columns that are probably not of interest to the users (those would still be available in the clinical_notes.json): sources, column_number, num_values, rng
* use values.option_code instead of introducing values.option_value
* table_name should match the suffix of the table in BQ - for most of the tables, it would be "clinical"

**Comment by G-White-ISB** [comment]
This items are now addressed in idc-dev-etl.clinical.clinical_meta

**Comment by fedorov** [comment]
Yes, all of this I think is addressed now, thank you!
