### ISSUE TITLE
[clinical] Capture provenance of the collection-specific columns

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/ETL#24]
Per discussion yesterday, it will be very useful to capture the provenance of the items in the per-collection metadata dictionary:
* what file they are coming from (+hash of that file)
* if the above is a zip file - which file from the zip file they come from
* what sheet, if applicable
* if there is a hierarchy of column names - include that hierarchy

**Comment by G-White-ISB** [comment]
Note: when the clinical data for one collection is split into two batches each column will have two source columns. Sometimes the original column name might be different between the sources - ie one batch may use 'Age' and another 'age' but they both map to the 'age' column in the final BQ table. But yes we can handles such situations in the captured provenance.
