### ISSUE TITLE
Map the patient identifier column in the clinical collections to the  DICOM patientID 

### ISSUE THREAD

**Issue by G-White-ISB** [ImagingDataCommons/ETL#27]
As discussed in #26 the patient identifier in the clinical collection may not be identical to the patientID in the DICOM file. There is sometimes a difference in format (ie handling of letter case etc) between the two. Each row in the clinical data must be mapped to the corresponding DICOM patientID attribute

**Comment by fedorov** [comment]
Not quite sure how this is different from #26, but ok!

**Comment by fedorov** [comment]
I think it's the same as #26, closing
