### ISSUE TITLE
Clinical data per-table metadata tracking

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/ETL#29]
To facilitate tracking of changes for the clinical data tables, we should probably introduce a table that will have one row per clinical table and would include:
* initial version of IDC data where that table was introduced
* version of IDC data where this table was modified
* collection_id it belongs to
* path to the file that was used to extract it and the hash of that file

We should discuss what else should be there, but I wanted to document this issue right away without coming up with a comprehensive list.

**Comment by G-White-ISB** [comment]
There is a new table clinical_summary with table level meta information about all the clinical tables. This table keeps track of the source data for each clinical table as well as how the source changes in time by tracking changes in its has value

**Comment by fedorov** [comment]
clinical_summary is now clinical_meta_table, right? If yes, this can be closed.

**Comment by G-White-ISB** [comment]
Yes clinical_summary was replaced by clinical_meta_table
