### ISSUE TITLE
Consider renaming "variable" to "column" in "column_metadata"

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/ETL#34]
I am coming up with those ideas as I work on a notebook demonstrating the use of this content. No action right now, but as I think about it, referring to those as "variables" may be confusing.

**Comment by G-White-ISB** [comment]
That make sense to me.

**Comment by G-White-ISB** [comment]
"variable" has been renamed to "column", and "variable_label" is renamed to "column_label"
