### ISSUE TITLE
Consider adding instance size to the BQ tables

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/ETL#4]
It will probably be quite valuable to the users to know how much space the cohort will take when downloaded. In particular, this will be important for the user in order to allocate sufficient disk space when downloading the data to the VM.

I think we should add a column with the size for each instance we are indexing. We discussed this with @wlongabaugh and he also thought it makes sense. What do you think @bcli4d?

**Comment by wlongabaugh** [comment]
And provide the sum as part of the interactive cohort download.

**Comment by bcli4d** [comment]
Instance size is in the auxiliary metadata table. Are you asking for it to be added to dicom_all? We can do. In the next update after the Tuesday release?

**Comment by fedorov** [comment]
I missed that it is in the aux table - this is great! Yes, I think it makes sense to add it to dicom_all on the next update, and coordinate with @s-paquette to provide this information to the user in the portal UI.

**Comment by fedorov** [comment]
instance_size has been added to dicom_all.
