### ISSUE TITLE
Values for `dicom_patient_id` are invalid for the `acrin_6698` collection

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/ETL#43]
It appears that the clinical table is referring to the patients by suffixes of DICOM `PatientID`. To get the actual patient ID we need to prepend that suffix with `ACRIN-6698-`.

Going forward, when populating `dicom_patient_id` column, there should be a check that all IDs included in that column for the specific clinical data table are **all** present among the values of `PatientID` selected from `dicom_all` for that specific table.

**Comment by G-White-ISB** [comment]
Will add a check of all IDs by v12.

**Comment by G-White-ISB** [comment]
The ACRIN 6698 dicom_patient_id values now have the correct form. The clinical data exporter now checks these values against the  PatientID value in dicom_all when the clinical dataset is created
